### ISSUE TITLE
Disabled connection in ConnectionPools "availableConnections"

### ISSUE THREAD

**Issue by bgloeckle** [diqube/diqube#98]
Disabled connection is put into availableConnections of ConnectionPool. This must not happen.

```
java.lang.IllegalStateException: Connection disabled!
	at org.diqube.connection.Connection.getService(Connection.java:66) ~[classes/:na]
	at org.diqube.connection.ConnectionPool.reserveAvailableConnection(ConnectionPool.java:342) ~[classes/:na]
	at org.diqube.connection.ConnectionPool.reserveConnection(ConnectionPool.java:240) ~[classes/:na]
	at org.diqube.server.querymaster.query.QueryServiceHandler.asyncExecuteQuery(QueryServiceHandler.java:247) ~[classes/:na]
	at org.diqube.remote.query.thrift.QueryService$Processor$asyncExecuteQuery.getResult(QueryService.java:267) [classes/:na]
	at org.diqube.remote.query.thrift.QueryService$Processor$asyncExecuteQuery.getResult(QueryService.java:1) [classes/:na]
	at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:39) [libthrift-0.9.3.jar:0.9.3]
	at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:39) [libthrift-0.9.3.jar:0.9.3]
	at org.diqube.connection.integrity.IntegrityCheckingProtocol$IntegrityCheckDisablingProcessor.process(IntegrityCheckingProtocol.java:219) [classes/:na]
	at org.apache.thrift.TMultiplexedProcessor.process(TMultiplexedProcessor.java:123) [libthrift-0.9.3.jar:0.9.3]
	at org.apache.thrift.server.AbstractNonblockingServer$FrameBuffer.invoke(AbstractNonblockingServer.java:518) [libthrift-0.9.3.jar:0.9.3]
	at org.apache.thrift.server.Invocation.run(Invocation.java:18) [libthrift-0.9.3.jar:0.9.3]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_66-internal]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_66-internal]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_66-internal]
 ```

**Comment by bgloeckle** [comment]
Seems to be that a single Connection was released multiple times: A cancel request was executed simultaneously to the query exeuction being done: Both the cancel released the connection and the normal cleanup (a cancel thread and the query-master thread). We should add an atomic field to a connection to indicate if it has been released already. In addition to that, we might want to centralize query cleanup in the QueryServiceHandler code and synchronize that.

**Comment by bgloeckle** [comment]
Closing this as the problem should've been fixed. Build succeeds.
